package com.example.employee.model;

import java.time.Instant;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import com.example.employee.attendance.AttendanceEventType;

@Document(collection = "attendance_events")
public class AttendanceEventDocument {

    @Id
    private String id;

    /**
     * Unique ID generated by the employee agent.
     * Used for idempotency and duplicate-event protection.
     *
     * MongoDB enforces uniqueness for this field.
     */
    @Indexed(unique = true)
    @Field("eventId")
    private String eventId;

    @Field("employeeCode")
    private String employeeCode;

    @Field("deviceId")
    private String deviceId;

    @Field("eventType")
    private AttendanceEventType eventType;

    @Field("timestamp")
    private Instant timestamp;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getEventId() {
        return eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    public String getEmployeeCode() {
        return employeeCode;
    }

    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public AttendanceEventType getEventType() {
        return eventType;
    }

    public void setEventType(AttendanceEventType eventType) {
        this.eventType = eventType;
    }

    public Instant getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Instant timestamp) {
        this.timestamp = timestamp;
    }
}